(cl:defpackage beginner_tutorials-srv
  (:use )
  (:export
   "TURTLE_HISTORY"
   "<TURTLE_HISTORY-REQUEST>"
   "TURTLE_HISTORY-REQUEST"
   "<TURTLE_HISTORY-RESPONSE>"
   "TURTLE_HISTORY-RESPONSE"
   "TURTLE_LETTERS"
   "<TURTLE_LETTERS-REQUEST>"
   "TURTLE_LETTERS-REQUEST"
   "<TURTLE_LETTERS-RESPONSE>"
   "TURTLE_LETTERS-RESPONSE"
  ))

