// Generated by gencpp from file beginner_tutorials/turtle_letters.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TURTLE_LETTERS_H
#define BEGINNER_TUTORIALS_MESSAGE_TURTLE_LETTERS_H

#include <ros/service_traits.h>


#include <beginner_tutorials/turtle_lettersRequest.h>
#include <beginner_tutorials/turtle_lettersResponse.h>


namespace beginner_tutorials
{

struct turtle_letters
{

typedef turtle_lettersRequest Request;
typedef turtle_lettersResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turtle_letters
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::turtle_letters > {
  static const char* value()
  {
    return "f5f0130de4c436554e39ca1270e27617";
  }

  static const char* value(const ::beginner_tutorials::turtle_letters&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::turtle_letters > {
  static const char* value()
  {
    return "beginner_tutorials/turtle_letters";
  }

  static const char* value(const ::beginner_tutorials::turtle_letters&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::turtle_lettersRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::turtle_letters >
template<>
struct MD5Sum< ::beginner_tutorials::turtle_lettersRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::turtle_letters >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_lettersRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::turtle_lettersRequest> should match
// service_traits::DataType< ::beginner_tutorials::turtle_letters >
template<>
struct DataType< ::beginner_tutorials::turtle_lettersRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::turtle_letters >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_lettersRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::turtle_lettersResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::turtle_letters >
template<>
struct MD5Sum< ::beginner_tutorials::turtle_lettersResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::turtle_letters >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_lettersResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::turtle_lettersResponse> should match
// service_traits::DataType< ::beginner_tutorials::turtle_letters >
template<>
struct DataType< ::beginner_tutorials::turtle_lettersResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::turtle_letters >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_lettersResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TURTLE_LETTERS_H
