// Generated by gencpp from file beginner_tutorials/turtle_historyRequest.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TURTLE_HISTORYREQUEST_H
#define BEGINNER_TUTORIALS_MESSAGE_TURTLE_HISTORYREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace beginner_tutorials
{
template <class ContainerAllocator>
struct turtle_historyRequest_
{
  typedef turtle_historyRequest_<ContainerAllocator> Type;

  turtle_historyRequest_()
    : info()  {
    }
  turtle_historyRequest_(const ContainerAllocator& _alloc)
    : info(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _info_type;
  _info_type info;





  typedef boost::shared_ptr< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> const> ConstPtr;

}; // struct turtle_historyRequest_

typedef ::beginner_tutorials::turtle_historyRequest_<std::allocator<void> > turtle_historyRequest;

typedef boost::shared_ptr< ::beginner_tutorials::turtle_historyRequest > turtle_historyRequestPtr;
typedef boost::shared_ptr< ::beginner_tutorials::turtle_historyRequest const> turtle_historyRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator2> & rhs)
{
  return lhs.info == rhs.info;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator1> & lhs, const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace beginner_tutorials

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c10fc26d5cca9a4b9114f5fc5dea9570";
  }

  static const char* value(const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc10fc26d5cca9a4bULL;
  static const uint64_t static_value2 = 0x9114f5fc5dea9570ULL;
};

template<class ContainerAllocator>
struct DataType< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "beginner_tutorials/turtle_historyRequest";
  }

  static const char* value(const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string info\n"
;
  }

  static const char* value(const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.info);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct turtle_historyRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::beginner_tutorials::turtle_historyRequest_<ContainerAllocator>& v)
  {
    s << indent << "info: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.info);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TURTLE_HISTORYREQUEST_H
