// Generated by gencpp from file beginner_tutorials/turtle_history.msg
// DO NOT EDIT!


#ifndef BEGINNER_TUTORIALS_MESSAGE_TURTLE_HISTORY_H
#define BEGINNER_TUTORIALS_MESSAGE_TURTLE_HISTORY_H

#include <ros/service_traits.h>


#include <beginner_tutorials/turtle_historyRequest.h>
#include <beginner_tutorials/turtle_historyResponse.h>


namespace beginner_tutorials
{

struct turtle_history
{

typedef turtle_historyRequest Request;
typedef turtle_historyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct turtle_history
} // namespace beginner_tutorials


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::beginner_tutorials::turtle_history > {
  static const char* value()
  {
    return "61e5a00050969050ae93076978354c3f";
  }

  static const char* value(const ::beginner_tutorials::turtle_history&) { return value(); }
};

template<>
struct DataType< ::beginner_tutorials::turtle_history > {
  static const char* value()
  {
    return "beginner_tutorials/turtle_history";
  }

  static const char* value(const ::beginner_tutorials::turtle_history&) { return value(); }
};


// service_traits::MD5Sum< ::beginner_tutorials::turtle_historyRequest> should match
// service_traits::MD5Sum< ::beginner_tutorials::turtle_history >
template<>
struct MD5Sum< ::beginner_tutorials::turtle_historyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::turtle_history >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_historyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::turtle_historyRequest> should match
// service_traits::DataType< ::beginner_tutorials::turtle_history >
template<>
struct DataType< ::beginner_tutorials::turtle_historyRequest>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::turtle_history >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_historyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::beginner_tutorials::turtle_historyResponse> should match
// service_traits::MD5Sum< ::beginner_tutorials::turtle_history >
template<>
struct MD5Sum< ::beginner_tutorials::turtle_historyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::beginner_tutorials::turtle_history >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_historyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::beginner_tutorials::turtle_historyResponse> should match
// service_traits::DataType< ::beginner_tutorials::turtle_history >
template<>
struct DataType< ::beginner_tutorials::turtle_historyResponse>
{
  static const char* value()
  {
    return DataType< ::beginner_tutorials::turtle_history >::value();
  }
  static const char* value(const ::beginner_tutorials::turtle_historyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BEGINNER_TUTORIALS_MESSAGE_TURTLE_HISTORY_H
